### ISSUE TITLE
cmakelists file issue

### ISSUE THREAD

**Issue by leejiawei** [robotraconteur/robotraconteur#23]
Hi, everyone
when I include the file "robotraconteur_generated.h" in my cpp code. I got this error: fatal error: robotraconteur_generated.h: No such file or directory. And I got this error: error: ‘ROBOTRACONTEUR_SERVICE_TYPES’ was not declared in this scope
   ServerNodeSetup node_setup.

I knew something was wrong with my cmakelists file:

1. I cannot include "IMPORT_DIRS ${CMAKE_CURRENT_SOURCE_DIR}/../robdef" in my cmakelist. since no file.robdef can be found.

2. I cannot add ${RR_THUNK_HDRS} ${RR_THUNK_SRCS} to the add_executable() in cmakelists. 

Can anyone help me wiith it.

**Comment by johnwason** [comment]
Do you have a robdef file you are trying to use? The IMPORT_DIRS should point to the directory containing the robdef file. You can then specify the robdef file to generate from.

Be sure to have an

`include_directories(${CMAKE_CURRENT_BINARY_DIR})`

command in your CMake so it can find the generated header file.

**Comment by leejiawei** [comment]
> Do you have a robdef file you are trying to use? The IMPORT_DIRS should point to the directory containing the robdef file. You can then specify the robdef file to generate from.
> 
> Be sure to have an
> 
> `include_directories(${CMAKE_CURRENT_BINARY_DIR})`
> 
> command in your CMake so it can find the generated header file.

Thanks for the answer.

I figured out the cmakelists.txt. It seems that I miss added the RobotRaconteurCore to the target_link_libraries(...).

**Comment by leejiawei** [comment]
I still have an issue on "ServerNodeSetup node_setup(ROBOTRACONTEUR_SERVICE_TYPES, "nameXXX", numberXXX);

I got error: ‘ROBOTRACONTEUR_SERVICE_TYPES’ was not declared in this scope

**Comment by leejiawei** [comment]
> I still have an issue on "ServerNodeSetup node_setup(ROBOTRACONTEUR_SERVICE_TYPES, "nameXXX", numberXXX);
> 
> I got error: ‘ROBOTRACONTEUR_SERVICE_TYPES’ was not declared in this scope

I don't see any cpp definitions in example codes

**Comment by johnwason** [comment]
You will need a robdef file to describe the service. This robdef file needs to be passed to the ROBOTRACONTEUR_GENERATE_THUNK command. It will then generate the `robotraconteur_generated.h` file you can include. This generated header file contains the definition of `ROBOTRACONTEUR_SERVICE_TYPES`

**Comment by leejiawei** [comment]
> You will need a robdef file to describe the service. This robdef file needs to be passed to the ROBOTRACONTEUR_GENERATE_THUNK command. It will then generate the `robotraconteur_generated.h` file you can include. This generated header file contains the definition of `ROBOTRACONTEUR_SERVICE_TYPES`

Thanks Dr.johnwason,
My code is working very fine now.
Thanks for the great help

**Comment by johnwason** [comment]
No problem, glad it is working!
