### ISSUE TITLE
issues with RobotRaconteurNode::s()->RegisterService()

### ISSUE THREAD

**Issue by leejiawei** [robotraconteur/robotraconteur#24]
Hi 

I am currently trying to mimic the i-robotcreatesevice example.
However, once I used RobotRaconteurNode::s()->RegisterService("Create","kingen",create);

I got an error: no matching function for call to ‘RobotRaconteur::RobotRaconteurNode::RegisterService(const char [7], const char
[7], boost::shared_ptr<Create_impl>&)’

however, I do write RR_SHARED_PTR<Create_impl> create=RR_MAKE_SHARED<Create_impl>(port); before the RobotRaconteurNode::s()->RegisterService

please help me

Thanks

**Comment by leejiawei** [comment]
also, when I use the sentence:

ServerNodeSetup node_setup(ROBOTRACONTEUR_SERVICE_TYPES, "kingen", 2355);

I got:

![Screenshot from 2019-08-05 23-30-06](https://user-images.githubusercontent.com/18585616/62476231-2a7afc00-b7d9-11e9-8db1-06095dc80e27.png)

**Comment by johnwason** [comment]
Did you build Robot Raconteur following the ROS instructions? That may help.

It is hard to tell from the info you have provided what is wrong. Can you create a repository and send me a link? If you want to keep it private GitLab will allow you to only share the code with me.

**Comment by leejiawei** [comment]
> Did you build Robot Raconteur following the ROS instructions? That may help.
> 
> It is hard to tell from the info you have provided what is wrong. Can you create a repository and send me a link? If you want to keep it private GitLab will allow you to only share the code with me.

It seems that the command "catkin_make_isolated --cmake-args -DROBOTRACONTEUR_ROS=1"  is really important.
after typing the command, everything goes smoothly.

Thanks for pointing this out.

and 

Thanks for the help. sincerely

This issue can be closed

**Comment by leejiawei** [comment]
> Did you build Robot Raconteur following the ROS instructions? That may help.
> 
> It is hard to tell from the info you have provided what is wrong. Can you create a repository and send me a link? If you want to keep it private GitLab will allow you to only share the code with me.

By typing the command"catkin_make_isolated --cmake-args -DROBOTRACONTEUR_ROS=1", the second issue is solved. but not the first one.

**Comment by leejiawei** [comment]
I don't mind to share my code.
sir you can see it here:

[issue.tar.gz](https://github.com/robotraconteur/robotraconteur/files/3468487/issue.tar.gz)

**Comment by johnwason** [comment]
It doesn't look like your Create_impl class is inheriting from a Robot Raconteur generated type, and your robdef file doesn't contain a type. The service object must inherit from a type generated by Robot Raconteur. For instance, ::experimental::create2::Create_imple is a type generated from experimental.create2.robdef. Since your class does not inherit from RRObject through a Robot Raconteur generated type, it cannot be used as an argument for RegisterService.

**Comment by leejiawei** [comment]
> It doesn't look like your Create_impl class is inheriting from a Robot Raconteur generated type, and your robdef file doesn't contain a type. The service object must inherit from a type generated by Robot Raconteur. For instance, ::experimental::create2::Create_impl is a type generated from experimental.create2.robdef. Since your class does not inherit from RRObject through a Robot Raconteur generated type, it cannot be used as an argument for RegisterService.

oh, I see, thanks sir
I am gonna try this out.

**Comment by leejiawei** [comment]
Sir,

I think I got the most of the codes running fine.

however, I got an error when I tried to define a new function both in robdef and the main cpp file.

for example, 

if I define a function named stop() under the the class creat_impl.

class Create_impl{
.....
   virtual void Stop();
....
}

void Create_impl::Stop(){
  .......
}

and in robdef file
## I wrote:....
object Create

    function void Stop()
	
end

once I compile the code, I got:

CMakeFiles/KinovaEndEffector.dir/experimental__create2_stubskel.cpp.o: In function `experimental::create2::Create_stub::async_Stop(boost::function<void (boost::shared_ptr<Robot
Raconteur::RobotRaconteurException>)>, int)':
experimental__create2_stubskel.cpp:(.text+0x50b3): undefined reference to `RobotRaconteur::ServiceStub::AsyncProcessRequest(boost::intrusive_ptr<RobotRaconteur::MessageEntry>, boost::fu
nction<void (boost::intrusive_ptr<RobotRaconteur::MessageEntry>, boost::shared_ptr<RobotRaconteur::RobotRaconteurException>)>&&, int)'
collect2: error: ld returned 1 exit status

**Comment by johnwason** [comment]
I realized there was a typo on my previous response. It should have said ::experimental::create2::Create_default_impl is generated by Robot Raconteur. You should extend from a *_default_impl generated class.

Make sure you are including the generated cpp file as well. This most recent error suggests you are missing a generated source file.

**Comment by leejiawei** [comment]
In my own understanding:

First, I should define a type in robdef file, say: a function called stop() which is:

object Create
	function void Stop()
end

This tells my program that I defined a type.

Second, Inside my code, I include  "#include "robotraconteur_generated.h" " and "using namespace ::experimental::create2"; and then, in my own 
defined class I inherit the RR generated type:

class Create_impl : public Create_default_impl, public boost::enable_shared_from_this<Create_impl> {
 void Stop(){

      }
};

I got the same error: undefined reference.

So, I have no clue what is wrong here.  I did use the inheritance "public Create_default_impl" in my class create_impl

**Comment by johnwason** [comment]
It seems like you are missing the generated CPP file. Can you confirm that experimental__create2__stubskel.cpp is being included in the build?

**Comment by leejiawei** [comment]
> It seems like you are missing the generated CPP file. Can you confirm that experimental__create2__stubskel.cpp is being included in the build?

every time, when I do catkin_make, if there had an error, I can always see the notification from the console: 

CMakeFiles/KinovaEndEffector.dir/experimental__create2_stubskel.cpp.o: In function `experimental::create2::Create_stub::async_Stop(boost::function<void (boost::shared_ptr<RobotRaconteur
::RobotRaconteurException>)>, int)':

Which tells me that in somewhere there is a file called "experimental__create2_stubskel.cpp.o" has been built automatically.

But, I have neither manually built this file in my cpp program nor cmakelist.txt.

In a word, I don't know how to build this experimental__create2__stubskel.cpp

by the way, thanks for the help, sir

**Comment by johnwason** [comment]
This is a very strange error. My best guess is that there is stale intermediate build files leading to inconsistent symbols. Are you always running `catkin_make_isolated`, or did you run `catkin_make` as well?

If you send me your current code I will take a look again.

**Comment by leejiawei** [comment]
I only use catkin_make.

Please also see my code:
which has the cpp file, robdef file as well as cmakelist.txt file.

[issue2.tar.gz](https://github.com/robotraconteur/robotraconteur/files/3478825/issue2.tar.gz)

**Comment by johnwason** [comment]
Ok, before I continue troubleshooting, please try the following:

1. Delete everything in `catkin_ws` **except** for your `src/` directory.
2. Run `catkin_make_isolated -DROBOTRACONTEUR_ROS=1`
3. Source `devel_isolated/setup.bash`
4. Run `catkin_make_isolated -DROBOTRACONTEUR_ROS=1`
5. Always build using `catkin_make_isolated`. Don't use `catkin_make`, there is no benefit and it can lead to a lot of problems.

**Comment by leejiawei** [comment]
> I only use catkin_make.
> 
> Please also see my code:
> which has the cpp file, robdef file as well as cmakelist.txt file.
> 
> [issue2.tar.gz](https://github.com/robotraconteur/robotraconteur/files/3478825/issue2.tar.gz)

if I don't define any functions in robdef file, my code works fine, but as long as I define a type in robdef, then I will definitely get an error. 

In cmakelist, I linked my robdef file  as well

**Comment by leejiawei** [comment]
I have done all the steps.
but the old issue is still there.

I think I am gonna continue my work tomorrow

Thanks for helping me patiently

Sincerely

**Comment by johnwason** [comment]
I see the problem - you need to use the new format for referencing the Robot Raconteur library. ${RobotRaconteur_LIBRARY} is no longer used. Instead use the `RobotRaconteurCore` target. See the example here:

https://github.com/robotraconteur/RobotRaconteur_CPP_Examples/blob/8991b3c4eb4a403578d81de5747114dadf58fbea/iRobotCreateService/CMakeLists.txt#L22

**Comment by leejiawei** [comment]
> I see the problem - you need to use the new format for referencing the Robot Raconteur library. ${RobotRaconteur_LIBRARY} is no longer used. Instead use the `RobotRaconteurCore` target. See the example here:
> 
> https://github.com/robotraconteur/RobotRaconteur_CPP_Examples/blob/8991b3c4eb4a403578d81de5747114dadf58fbea/iRobotCreateService/CMakeLists.txt#L22

I changed my add_target_link as what the example has. 

target_link_libraries(KinovaEndEffector RobotRaconteurCore ${catkin_LIBRARIES} ${OpenCV_LIBS} ${Boost_LIBRARIES} ${RobotRaconteurCore_Extra_Libraries})

But the same error shows up as usual.

CMakeFiles/KinovaEndEffector.dir/experimental__create2_stubskel.cpp.o: In function `experimental::create2::Create_stub::async_Stop(boost::function<void (boost::shared_ptr<RobotRaconteur
::RobotRaconteurException>)>, int)':
experimental__create2_stubskel.cpp:(.text+0x3b79): undefined reference to `RobotRaconteur::ServiceStub::AsyncProcessRequest(boost::intrusive_ptr<RobotRaconteur::MessageEntry>, boost::fu
nction<void (boost::intrusive_ptr<RobotRaconteur::MessageEntry>, boost::shared_ptr<RobotRaconteur::RobotRaconteurException>)>&&, int)'
collect2: error: ld returned 1 exit status

I don't think the issue is caused by these libraries. Somehow, the computer doesn't recognize my robdef function, thus can't use it in my main code.
Is there any thing to do with the location of my robdef file?

My robdef is located at : /home/jl888/catkin_ws/src/robdef

so In my cmakelist.txt.

I wrote: IMPORT_DIRS ${CMAKE_CURRENT_SOURCE_DIR} /home/jl888/catkin_ws/src/robdef

**Comment by johnwason** [comment]
The problem is not in the wrappers, it is when linking against the RobotRaconteurCore library. It is not finding a symbol in tho Robot Raconteur library.

It looks like you have enabled C++11 in your CMakeLists.txt. Unfortunately ROS 1 does not support C++11, and Robot Raconteur does not build with C++11 support when using ROS Kinetic on Ubuntu Xenial. On ROS Melodic with Ubuntu Bionic this shouldn't be a problem.

Try disabling C++11 and use the full type names instead of type aliases. These aliases are defined at the end of the header files in Robot Raconteur. For instance, see here:

https://github.com/robotraconteur/robotraconteur/blob/aa97cded671dce6eab994f06197f3c4e4f3c4706/RobotRaconteurCore/include/RobotRaconteur/DataTypes.h#L1727

Use the long form, for instance `RR_INTRUSIVE_PTR<RRArray<double> >` instead of `RRArrayPtr<doube>`

**Comment by leejiawei** [comment]
> The problem is not in the robdef, it is when linking against the RobotRaconteurCore library. It is not finding a symbol in tho Robot Raconteur library.
> 
> It looks like you have enabled C++11 in your CMakeLists.txt. Unfortunately ROS 1 does not support C++11, and Robot Raconteur does not build with C++11 support when using ROS Kinetic on Ubuntu Xenial. On ROS Melodic with Ubuntu Bionic this shouldn't be a problem.
> 
> Try disabling C++11 and use the full type names instead of type aliases. These aliases are defined at the end of the header files in Robot Raconteur. For instance, see here:
> 
> https://github.com/robotraconteur/robotraconteur/blob/aa97cded671dce6eab994f06197f3c4e4f3c4706/RobotRaconteurCore/include/RobotRaconteur/DataTypes.h#L1727-L1762
> 
> Use the long form, for instance `RR_INTRUSIVE_PTR<RRArray<double> >` instead of `RRArrayPtr<doube>`

I disabled c++11 in my cmakelist file,  and I define an empty function Stop() both in my cpp code and robdef file.

however, RR still won't recognize it.

........I am so frustrated........    *__*

**Comment by johnwason** [comment]
What version of ROS and Ubuntu are you using?

It is possible that the code did not recompile without C++11 and it is still using the old intermediate compiler products again.

If you send the modified code I will try to replicate but I have not seen this issue before on ROS.

**Comment by leejiawei** [comment]
> What version of ROS and Ubuntu are you using?
> 
> It is possible that the code did not recompile without C++11 and it is still using the old intermediate compiler products again.
> 
> If you send the modified code I will try to replicate but I have not seen this issue before on ROS.

The ROS version is kinetic and the ubuntu version is:
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.6 LTS
Release:        16.04
Codename:       xenial

**Comment by leejiawei** [comment]
The compressed code is given here:
[issue3.tar.gz](https://github.com/robotraconteur/robotraconteur/files/3483483/issue3.tar.gz)

**Comment by johnwason** [comment]
In your CMakeLists.txt file, there is the line

`set(CMAKE_CXX_STANDARD 14)`

This is causing the following command to be executed to build the thunk code cpp file:

`/usr/bin/c++   -DBOOST_ALL_NO_LIB -DROSCONSOLE_BACKEND_LOG4CXX -DROS_BUILD_SHARED_LIBS=1 -DROS_PACKAGE_NAME=\"test\" -I/opt/ros/kinetic/include/libfranka -I/home/wasonj/catkin_ws/build_isolated/test -I/home/wasonj/catkin_ws/src/test/include -I/home/wasonj/catkin_ws/devel_isolated/kortex_driver/include -I/opt/ros/kinetic/include -I/opt/ros/kinetic/share/xmlrpcpp/cmake/../../../include/xmlrpcpp -I/home/wasonj/catkin_ws/devel_isolated/robotraconteur/include  -std=gnu++14 -o CMakeFiles/KinovaEndEffector.dir/experimental__create2_stubskel.cpp.o -c /home/wasonj/catkin_ws/build_isolated/test/experimental__create2_stubskel.cpp
`
One of the flags here is `-std=gnu++14`, which is C++14 the successor to C++11. Currently Robot Raconteur is being built for C++98, which has different capabilities.  The Robot Raconteur library must be compiled with C++11 enabled if the user wants C++11 support, but on ROS by default it is set to C++98. Support for C++11 is much better in ROS melodic, and this hasn't been a problem so far.

Remove the C++14 line and try again.

**Comment by leejiawei** [comment]
Thanks sir

I disabled the c++11 and c++ 14 in my  cmakelist.txt
and everything goes well.

**Comment by leejiawei** [comment]
In the end, I would like to thank Dr.John wason for everything you have done for me.
And I hope this question can be opened for everyone, so that my issue can be used as a good example and a lesson for anyone who has the similar issues.

**Comment by johnwason** [comment]
Glad to help

The issue will still be visible to google even when closed, so others will be able to find it if they encounter similar problems.

Another side note, when RobotRaconteurGen is built for ROS it will search the `robdef` directory in packages for the service definition files, so you shouldn't need the INCLUDE_DIRS in CMakeLists.txt.

**Comment by leejiawei** [comment]
Also, In my childish opinion, personally, I think RR is so great. and it should be commercialized in the future.
As a roboticist, I rarely can find a tool which can be used as a bridge that connects robots and different platforms together. However, this is very important, especially in labs.
I hope RR can be applied widely in someday.

**Comment by johnwason** [comment]
Thanks, glad to hear you find it useful!

RR has received a grant from the ARM Institute and is currently in the process of being commercialized.
