### ISSUE TITLE
Rosdep cannot find all required resources to answer your query Missing resource robotraconteur

### ISSUE THREAD

**Issue by leejiawei** [robotraconteur/robotraconteur#26]
Sir,

I am facing a new issue, This time I tried to install RR on ubuntu 18.04 Bionic, ros Melodic.

I first execute all the commands that are required on GITHUB, 

Then, I want to build RR within ROS. 

steps:

1. delete all files in catkin_ws, leave only src file.

2. cope RR-master to the src file.

3. rosdep install robotraconteur (the command I used for rosdep installing

error:

Rosdep cannot find all required resources to answer your query
Missing resource robotraconteur
ROS path [0]=/opt/ros/melodic/share/ros
ROS path [1]=/opt/ros/melodic/share

4. catkin_make_isolated --cmake-args -DROBOTRACONTEUR_ROS=1

error..

CMake Error at /usr/share/cmake-3.10/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find SWIG (missing: SWIG_EXECUTABLE SWIG_DIR) (Required is at
  least version "4.0.0")

which says that I don't have swig 4.0,  However, I did did install the swig4.0 by instruction.

I don't know what the issue is....

Thanks for helping me

Jiawei

**Comment by leejiawei** [comment]
Thank sir

I will try this tonight

Sincerely

**Comment by leejiawei** [comment]
I think the RR build is working fine now, However, my source devel_isloated/setup.bash is incoorect, the  path is somehow in devel_isloated/robotractonteur/setup.bash.

which is weird.

**Comment by leejiawei** [comment]
my package cannot be found

**Comment by johnwason** [comment]
This is a problem with catkin_make_isolated that I have encountered before. Can you source the setup.bash in your package directory under devel_isolated?

**Comment by leejiawei** [comment]
yes, the source command is working

**Comment by leejiawei** [comment]
Another question:

My code is compiled with catkin_make_isolated well. no issues are found.

however, once I run the "rosrun packagename, my file(cpp) I got "Expected 1 parameter of port device"

So under my code main(....)
{
   if (argc <2) 
	{
		cout << "Expected 1 parameter of port device" << endl;
		return -1;
	}

  std::string port = string(argv[1]);
}

I don't know what happened with my port.

**Comment by johnwason** [comment]
Generally the command would be something like:

`rosrun my_package my_command /dev/ttyUSB0`

**Comment by johnwason** [comment]
Can I close this issue?

**Comment by leejiawei** [comment]
Thank you  sir

You can close the issue
