### ISSUE TITLE
port issue

### ISSUE THREAD

**Issue by leejiawei** [robotraconteur/robotraconteur#27]
Sir:

I create a port named: std::string port = string("8080");

but,

RR_SHARED_PTR<Create_impl> create=RR_MAKE_SHARED<Create_impl>(port);

gives me when I try running rosrun:

terminate called after throwing an instance of 'boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<boost::system::system_error> >'
  what():  open: No such file or directory
Aborted (core dumped)

**Comment by johnwason** [comment]
The port here is the serial port, so something like `/dev/ttyUSB0`, not the TCP port.

**Comment by leejiawei** [comment]
Thanks professor
