### ISSUE TITLE
Running Nodes as Services (Sudo)

### ISSUE THREAD

**Issue by hehonglu123** [robotraconteur/robotraconteur#36]
starttool.service created under `/etc/systemd/system/`, 
![image](https://user-images.githubusercontent.com/44752310/131429580-1cac056c-6ab2-4407-980d-871695da3343.png)

After `systemctl enable starttool.service` and `systemctl start starttool.service`, I got
```
RobotRaconteur.RobotRaconteurPythonError.SystemResourceException: RobotRaconteur.SystemResourceError Home directory not set
```

**Comment by johnwason** [comment]
Fixed with #53
